# Note: this is a shared pipeline used by other repositories.
# Docs: https://docs.github.com/en/actions/using-workflows/reusing-workflows

on:
  workflow_call:
    secrets:
      githubToken:
        required: true
      algoliaAdminApiKey:
        required: true
    inputs:
      source:
        type: string
        required: true
        description: "(ex: 'Code Generator')"
      domain:
        type: string
        required: true
        description:
          "The root domain and path that will prefix all URLs (ex:
          'https://www.the-guild.dev/graphql/codegen/')"
      lockFilePath:
        type: string
        required: false
        default: algolia-lockfile.json
        description: Relative path from `website/` to the Algolia lockfile
      docsBaseDir:
        type: string
        required: false
        default: ./src/pages/
        description: Relative path from `website/` to nextra markdown pages root folder
      websiteDirectory:
        required: false
        type: string
        default: ./website/
      skipCommitLockFile:
        description: Prevent committing lockfile
        required: false
        type: boolean
        default: false

      # must match setup/actions.yml
      node-version:
        type: string
        description: Node.js version to use.
        required: false
      node-version-file:
        type: string
        description: File containing the version to use.
        required: false
      setup-working-directory:
        type: string
        description: Working directory for the env setup.
        required: false
        default: .

jobs:
  algolia-push-records:
    name: Push new records if changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up env
        id: env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}
          working-directory: ${{ inputs.setup-working-directory }}

      - name: Algolia push (non-pnpm)
        if: steps.env.outputs.package-manager != 'pnpm'
        run:
          ${{ steps.env.outputs.package-manager }} run theguild-nextra-algolia --publish -o ${{
          inputs.lockFilePath }} --source '${{ inputs.source }}' --domain ${{ inputs.domain }}
          --docsBaseDir ${{ inputs.docsBaseDir }}
        working-directory: ${{ inputs.websiteDirectory }}
        env:
          ALGOLIA_APP_ID: ANRJKXZTRW
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.algoliaAdminApiKey }}
          ALGOLIA_INDEX_NAME: searchv2_main

      - name: Algolia push (pnpm)
        if: steps.env.outputs.package-manager == 'pnpm'
        run:
          pnpm --filter ${{ inputs.websiteDirectory }} run theguild-nextra-algolia --publish -o ${{
          inputs.lockFilePath }} --source '${{ inputs.source }}' --domain ${{ inputs.domain }}
          --docsBaseDir ${{ inputs.docsBaseDir }}
        working-directory: ${{ inputs.setup-working-directory }}
        env:
          ALGOLIA_APP_ID: ANRJKXZTRW
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.algoliaAdminApiKey }}
          ALGOLIA_INDEX_NAME: searchv2_main

      - name: Diff to file
        if: always()
        id: diff_result
        run: |
          OUTPUT=$(git diff ${{ inputs.websiteDirectory }}${{ inputs.lockFilePath }})
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "result=$OUTPUT" >> $GITHUB_OUTPUT

      - name: Commit algolia-lockfile.json
        if: ${{ !inputs.skipCommitLockFile && contains(steps.diff_result.outputs.result, 'diff') }}
        uses: EndBug/add-and-commit@v9
        with:
          commit: '${{ inputs.websiteDirectory }}${{ inputs.lockFilePath }}'
          message: Update algolia-lockfile.json
          default_author: github_actions
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
