# Note: this is a shared pipeline used by other repositories. 
# Docs: https://docs.github.com/en/actions/using-workflows/reusing-workflows

on:
  workflow_call:
    inputs:
      nodeVersion:
        required: false
        type: number
        default: 18
      script:
        required: true
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: the-guild-org/shared-config/setup@shared-setup
        name: setup env
        with:
          nodeVersion: ${{inputs.nodeVersion}}

      - name: ${{ inputs.script }}
        run: ${{ inputs.script }}
