# Note: this is a shared pipeline used by other repositories. 
# Docs: https://docs.github.com/en/actions/using-workflows/reusing-workflows

on:
  workflow_call:
    inputs:
      nodeVersion:
        required: false
        type: number
        default: 18
      releaseScript:
        required: false
        type: string
        default: release
      createGithubReleases:
        required: false
        type: string
        default: aggregate
      githubReleaseName:
        required: false
        type: string
    secrets:
      githubToken:
        required: true
      npmToken:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: the-guild-org/shared-config/setup@shared-setup
        name: setup env
        with:
          nodeVersion: ${{inputs.nodeVersion}}

      - name: set version variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=date::$(date +"%B %d, %Y")"

      - name: release / pull_request
        id: changesets
        uses: dotansimha/changesets-action@v1.3.3
        with:
          publish: 'yarn ${{ inputs.releaseScript }}'
          commit: 'chore(release): update monorepo packages versions'
          title: 'Upcoming Release Changes'
          createGithubReleases: ${{ inputs.createGithubReleases }}
          githubReleaseName: ${{ inputs.githubReleaseName || steps.vars.outputs.date }}
        env:
          NPM_TOKEN: ${{ secrets.npmToken }}
          GITHUB_TOKEN: ${{ secrets.githubToken }}
